const products = [
  {
    id: 1,
    name: "Gold Chain Necklace",
    price: 2499,
    category: "necklace",
    image: "https://via.placeholder.com/300",
    description: "Elegant 22K gold chain perfect for daily wear.",
    rating: 4.5,
    stock: 10,
    metal: "gold",
  },
  {
    id: 2,
    name: "Diamond Stud Earrings",
    price: 4999,
    category: "earrings",
    image: "https://via.placeholder.com/300",
    description: "Classic diamond studs with premium shine.",
    rating: 4.8,
    stock: 5,
    metal: "diamond",
  },
  {
    id: 3,
    name: "Silver Charm Bracelet",
    price: 1299,
    category: "bracelet",
    image: "https://via.placeholder.com/300",
    description: "Stylish silver bracelet with customizable charms.",
    rating: 4.2,
    stock: 15,
    metal: "silver",
  },
  {
    id: 4,
    name: "Rose Gold Ring",
    price: 1999,
    category: "ring",
    image: "https://via.placeholder.com/300",
    description: "Minimalist rose gold ring for modern look.",
    rating: 4.4,
    stock: 8,
    metal: "gold",
  },
  {
    id: 5,
    name: "Pearl Drop Earrings",
    price: 1799,
    category: "earrings",
    image: "https://via.placeholder.com/300",
    description: "Elegant pearl earrings for special occasions.",
    rating: 4.6,
    stock: 12,
    metal: "pearl",
  },
  {
    id: 6,
    name: "Men's Steel Bracelet",
    price: 999,
    category: "bracelet",
    image: "https://via.placeholder.com/300",
    description: "Durable and stylish bracelet for men.",
    rating: 4.1,
    stock: 20,
    metal: "steel",
  },
];

export default products;
